const palette = {
  orange: "#FF6B35",
  orangeLight: "#FF8C5A",
  amber: "#FFA033",
  cream: "#F5E6D0",
  brown: "#8B5E3C",
  darkBrown: "#4A3728",
  charcoal: "#1A1A1A",
  darkSurface: "#242424",
  darkCard: "#2E2E2E",
  darkBorder: "#3A3A3A",
  white: "#FFFFFF",
  offWhite: "#F8F8F8",
  lightSurface: "#FAFAFA",
  lightCard: "#FFFFFF",
  lightBorder: "#EBEBEB",
  sepiaBg: "#F4ECD8",
  sepiaCard: "#EDE3D0",
  sepiaText: "#3B2A1A",
  sepiaAccent: "#8B6914",
  textLight: "#666666",
  textMuted: "#999999",
  success: "#34C759",
  error: "#FF3B30",
  blue: "#007AFF",
  downloading: "#0A84FF",
};

export type Theme = "dark" | "light" | "sepia";

export const ThemeColors = {
  dark: {
    background: palette.charcoal,
    surface: palette.darkSurface,
    card: palette.darkCard,
    border: palette.darkBorder,
    text: palette.white,
    textSecondary: "#AAAAAA",
    textMuted: "#666666",
    accent: palette.orange,
    accentLight: palette.orangeLight,
    tabBar: palette.darkSurface,
    icon: "#AAAAAA",
    iconActive: palette.orange,
  },
  light: {
    background: palette.offWhite,
    surface: palette.lightSurface,
    card: palette.lightCard,
    border: palette.lightBorder,
    text: "#1A1A1A",
    textSecondary: "#555555",
    textMuted: "#999999",
    accent: palette.orange,
    accentLight: palette.orangeLight,
    tabBar: palette.white,
    icon: "#888888",
    iconActive: palette.orange,
  },
  sepia: {
    background: palette.sepiaBg,
    surface: palette.sepiaCard,
    card: palette.sepiaCard,
    border: "#D4C5A9",
    text: palette.sepiaText,
    textSecondary: "#6B5240",
    textMuted: "#9E8775",
    accent: palette.sepiaAccent,
    accentLight: "#B88B2A",
    tabBar: palette.sepiaCard,
    icon: "#8B7355",
    iconActive: palette.sepiaAccent,
  },
};

export default {
  orange: palette.orange,
  orangeLight: palette.orangeLight,
  amber: palette.amber,
  success: palette.success,
  error: palette.error,
  blue: palette.blue,
  downloading: palette.downloading,
};
