const palette = {
  orange: "#FF6B35",
  orangeLight: "#FF8C5A",
  amber: "#FFA033",
  cream: "#F5E6D0",
  brown: "#8B5E3C",
  darkBrown: "#4A3728",
  charcoal: "#1A1A1A",
  darkSurface: "#242424",
  darkCard: "#2E2E2E",
  darkBorder: "#3A3A3A",
  white: "#FFFFFF",
  offWhite: "#F8F8F8",
  lightSurface: "#FAFAFA",
  lightCard: "#FFFFFF",
  lightBorder: "#EBEBEB",
  sepiaBg: "#F4ECD8",
  sepiaCard: "#EDE3D0",
  sepiaText: "#3B2A1A",
  sepiaAccent: "#8B6914",
  textLight: "#666666",
  textMuted: "#999999",
  success: "#34C759",
  error: "#FF3B30",
  blue: "#007AFF",
  downloading: "#0A84FF",
};

export type Theme = "dark" | "light" | "sepia" | "amoled" | "night" | "cool";

export const ThemeColors = {
  dark: {
    background: palette.charcoal,
    surface: palette.darkSurface,
    card: palette.darkCard,
    border: palette.darkBorder,
    text: palette.white,
    textSecondary: "#AAAAAA",
    textMuted: "#666666",
    accent: palette.orange,
    accentLight: palette.orangeLight,
    tabBar: palette.darkSurface,
    icon: "#AAAAAA",
    iconActive: palette.orange,
  },
  light: {
    background: palette.offWhite,
    surface: palette.lightSurface,
    card: palette.lightCard,
    border: palette.lightBorder,
    text: "#1A1A1A",
    textSecondary: "#555555",
    textMuted: "#999999",
    accent: palette.orange,
    accentLight: palette.orangeLight,
    tabBar: palette.white,
    icon: "#888888",
    iconActive: palette.orange,
  },
  sepia: {
    background: palette.sepiaBg,
    surface: palette.sepiaCard,
    card: palette.sepiaCard,
    border: "#D4C5A9",
    text: palette.sepiaText,
    textSecondary: "#6B5240",
    textMuted: "#9E8775",
    accent: palette.sepiaAccent,
    accentLight: "#B88B2A",
    tabBar: palette.sepiaCard,
    icon: "#8B7355",
    iconActive: palette.sepiaAccent,
  },
  // NEW THEMES START HERE
  amoled: {
    background: "#000000", // Pure black for AMOLED
    surface: "#0A0A0A",
    card: "#0F0F0F",
    border: "#1A1A1A",
    text: "#FFFFFF",
    textSecondary: "#B0B0B0",
    textMuted: "#707070",
    accent: "#00E5FF", // Cyan accent for AMOLED
    accentLight: "#33EBFF",
    tabBar: "#000000",
    icon: "#B0B0B0",
    iconActive: "#00E5FF",
  },
  night: {
    background: "#0A0E1A", // Deep blue-black
    surface: "#111624",
    card: "#151C2A",
    border: "#1F2636",
    text: "#E8EDFF",
    textSecondary: "#9AA4C4",
    textMuted: "#5C6680",
    accent: "#FF6B35", // Warm orange for night reading
    accentLight: "#FF8C5A",
    tabBar: "#111624",
    icon: "#9AA4C4",
    iconActive: "#FF6B35",
  },
  cool: {
    background: "#E8F0F8", // Cool light blue-gray
    surface: "#F0F5FA",
    card: "#FFFFFF",
    border: "#DCE5EC",
    text: "#2C3E50",
    textSecondary: "#5A6E7E",
    textMuted: "#8FA0B0",
    accent: "#4A90E2", // Calm blue accent
    accentLight: "#6BA6F0",
    tabBar: "#FFFFFF",
    icon: "#6B7F8F",
    iconActive: "#4A90E2",
  },
};

export default {
  orange: palette.orange,
  orangeLight: palette.orangeLight,
  amber: palette.amber,
  success: palette.success,
  error: palette.error,
  blue: palette.blue,
  downloading: palette.downloading,
};
